Test role adds and deletes test data
CactuseSecurity/firewall-orchestrator pull request #1314
Opened 2021-11-26 16:45 UTC by alf-cactus

Test users are added with a random string. These are deleted after testing or upon a failure
PW length increased

2021-11-29 09:32 UTC, tpurschke requested changes
- version number is still 5.4.2 - you need to merge current develop branch
- fresh install works
- upgrade fails with error
```
TASK [test : middleware test get jwt valid creds] ***************************************************************************************************************************
fatal: [fworch-srv]: FAILED! => changed=false 
  connection: close
  content: '{"error":"A0002 Invalid credentials"}'
  content_length: '37'
  date: Mon, 29 Nov 2021 09:22:10 GMT
  elapsed: 0
  msg: 'Status code was 400 and not [200]: HTTP Error 400: Bad Request'
  redirected: false
  server: Microsoft-NetCore/2.0
  status: 400
  url: https://127.0.0.1:8888/AuthenticateUser/
```

2021-11-29 09:32 UTC, tpurschke commented on roles/sample-auth-data/tasks/auth_sample_data.yml
> +    when: sample_role_purpose is not match('test')
Why not "is match demo"?

2021-11-29 09:32 UTC, tpurschke commented on inventory/group_vars/sampleserver.yml
> +sample_postfix: demo
Would recommend using _demo as postfix

2021-11-29 09:32 UTC, tpurschke commented on roles/test/tasks/main.yml
> +    test_postfix: "test_{{ random_generated_pw }}"
Here also more universal with  "__test_..."

2021-11-29 09:32 UTC, tpurschke commented on roles/test/tasks/test-auth.yml
> +# curl --request POST --url http://127.0.0.1:8888/AuthenticateUser/ --header 'content-type: application/json' --data '{"Username":"user1_{{ test_postfix }}","Password":"cactus1"}'
Replace old API call

2021-11-29 09:48 UTC, tpurschke commented
after install & upgrade, the following test data was left behind (only in LDAP):
```console
fworch@debian11:~/etc/secrets$ ldapsearch -x -W -D cn=manager,ou=systemuser,ou=user,dc=fworch,dc=internal -y /usr/local/fworch/etc/secrets/ldap_manager_pw.txt "(ou=*_test_*)"
# extended LDIF
#
# LDAPv3
# base <dc=fworch,dc=internal> (default) with scope subtree
# filter: (ou=*_test_*)
# requesting: ALL
#

# tenant1_test_mGrZSKMlZZWCfoByHYxnswgvevdMtjtf, operator, user, fworch.interna
 l
dn: ou=tenant1_test_mGrZSKMlZZWCfoByHYxnswgvevdMtjtf,ou=operator,ou=user,dc=fw
 orch,dc=internal
objectClass: top
objectClass: organizationalUnit
ou: tenant1_test_mGrZSKMlZZWCfoByHYxnswgvevdMtjtf

# tenant2_test_mGrZSKMlZZWCfoByHYxnswgvevdMtjtf, operator, user, fworch.interna
 l
dn: ou=tenant2_test_mGrZSKMlZZWCfoByHYxnswgvevdMtjtf,ou=operator,ou=user,dc=fw
 orch,dc=internal
objectClass: top
objectClass: organizationalUnit
ou: tenant2_test_mGrZSKMlZZWCfoByHYxnswgvevdMtjtf
```

2021-12-02 10:40 UTC, alf-cactus commented on roles/sample-auth-data/tasks/auth_sample_data.yml
> +    when: sample_role_purpose is not match('test')
The role should work normally, even if someone changes sample_role_purpose

2021-12-02 10:42 UTC, alf-cactus commented on roles/test/tasks/test-auth.yml
> +# curl --request POST --url http://127.0.0.1:8888/AuthenticateUser/ --header 'content-type: application/json' --data '{"Username":"user1_{{ test_postfix }}","Password":"cactus1"}'
done

2021-12-02 10:44 UTC, alf-cactus commented
had a wrong filter for deleting ldap data, should work now

2021-12-02 10:57 UTC, alf-cactus commented on inventory/group_vars/sampleserver.yml
> +sample_postfix: demo
done

2021-12-02 10:57 UTC, alf-cactus commented on roles/test/tasks/main.yml
> +    test_postfix: "test_{{ random_generated_pw }}"
done

2021-12-03 15:57 UTC, tpurschke requested changes
- test fresh install worked ok
- upgrade directly afterwards threw error:
```
TASK [test : middleware test get jwt valid creds] *****************************************************************************************************************
fatal: [fworch-srv]: FAILED! => changed=false 
  connection: close
  content: A0002 Invalid credentials
  content_type: text/plain; charset=utf-8
  date: Fri, 03 Dec 2021 14:45:23 GMT
  elapsed: 0
  msg: 'Status code was 400 and not [200]: HTTP Error 400: Bad Request'
  redirected: false
  server: Kestrel
  status: 400
  transfer_encoding: chunked
  url: https://127.0.0.1:8888/api/AuthenticationToken/Get/

RUNNING HANDLER [test : delete test user and dir] *****************************************************************************************************************
ok: [fworch-srv]
```
even login with admin user was not possible anymore after this (invalid creds)
but direct ldap access works:
```
tim@debian11:~$ sudo -u fworch ldapwhoami -x -D uid=admin,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal -w fworch.1
dn:uid=admin,ou=tenant0,ou=operator,ou=user,dc=fworch,dc=internal
tim@debian11:~$ 

```

2021-12-13 19:01 UTC, tpurschke approved these changes
install & upgrade tested successfully
no left-overs from test install found
perfect!

2021-12-13 19:10 UTC, merged