Filterline rework + Restsharp lib update
CactuseSecurity/firewall-orchestrator pull request #1512
Opened 2022-01-31 15:05 UTC by NilsPur

closes #1411 (Restsharp update)
closes #1294 (Exact equals operator)
closes #1220 (GraphQl variable readable)
closes #1210 (Disabled filter)
closes #568 (Semantic check)

2022-02-01 09:43 UTC, tpurschke requested changes
issues:
- PDF report generation causes error "Export Report - Unclassified error: : One or more errors occurred. (Unable to load native library. The platform may be missing native dependencies (libjpeg62, etc). Or the current platform is not supported.)"
- report on freshly imported rules does not work (empty ruleset) - could this be related to change in roles/lib/files/FWO.Config.Api/ConfigDbAccess.cs line 25?

2022-02-01 23:10 UTC, NilsPur commented
Just looked into the timing problem. Fixed the issue on my sight. Does it work now @tpurschke

2022-02-02 08:12 UTC, tpurschke commented
could not reproduce yesterday's reporting issue with empty ruleset (neither pre-fix nor post-fix).
but feel more confident with time fixed version.
Now it's only the PDF issue. can you activate the preview version?

2022-02-06 13:01 UTC, tpurschke requested changes
see inline comments

2022-02-06 13:01 UTC, tpurschke commented on roles/lib/files/FWO.Report/FWO.Report.csproj
> +    <PackageReference Include="Haukcode.WkHtmlToPdfDotNet" Version="1.5.68" />
pls revert this

2022-02-07 13:38 UTC, NilsPur commented on roles/lib/files/FWO.Report/FWO.Report.csproj
> +    <PackageReference Include="Haukcode.WkHtmlToPdfDotNet" Version="1.5.68" />
Done

2022-02-07 16:28 UTC, merged