ip filter next
CactuseSecurity/firewall-orchestrator pull request #1652
Opened 2022-03-31 14:02 UTC by tpurschke

- filter included in ip network is working - but slow
- also upgrading to hasura 2.4.0

2022-03-31 18:37 UTC, abarz722 requested changes
The rest looks good. Maybe we'll have an index later for the performance

2022-03-31 18:37 UTC, abarz722 commented on roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterNetwork.cs
> +                                        [
Isn't this twice the same statement?
Maybe _lte and _gte should be changed in the second one?

2022-04-01 09:01 UTC, tpurschke commented on roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterNetwork.cs
> +                                        [
simplified

2022-04-01 11:31 UTC, abarz722 commented on roles/lib/files/FWO.Report.Filter/Ast/AstNodeFilterNetwork.cs
> +                                {{ obj_ip: {{ _gte: ${QueryVarNameLast2} }} }}
is this correct? I would expect the _lte, _gte the other way round

2022-04-01 11:43 UTC, abarz722 approved these changes

2022-04-01 14:42 UTC, merged