Some cleanup + small fixes
CactuseSecurity/firewall-orchestrator pull request #2058
Opened 2023-05-09 13:49 UTC by abarz722

- check for spaces + some docu pieces -> #2054
- warning color to yellow -> #2044
- some missing translations
- converge css class determination
- cleanup + renaming

2023-05-09 15:21 UTC, tpurschke requested changes

2023-05-09 15:21 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    Im Falle Fortigate: Um einen vollst&auml;ndigen Datenimport zu gew&auml;hrleisten, bitte in der Fortigate config den Seitenumbruch deaktivieren, damit beim Kommando "show full-configuration" die
ohne "zu"

2023-05-09 15:21 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    F&uuml;r Fortinet, Barracuda, Juniper muss die IP vom aufl&ouml;sbaren Namen des Firewallgateways spezifiziert werden.
F&uuml;r alle übrigen Firewall-Plattformen, bei denen es es kein separates Management gibt, muss die IP oder der aufl&ouml;sbare Name des Firewallgateways spezifiziert werden

2023-05-09 15:21 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    For Fortinet, Barracuda, Juniper you need to specify the IP or resolvable name of the firewall gateway.
For all other firewall platforms which do not possess a separate management,  use the IP address or the resolvable name of the firewall gateway.

2023-05-09 15:21 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    Bitte kein RSA benutzen, da zumindest FortiGate ein Problem mit RSA-Schl&uuml;sseln zu haben scheint.<br>
Bitte für ssh-basierten legacy FortiGate Zugriff kein RSA benutzen, da es hier ein Problem mit RSA-Schl&uuml;sseln zu geben scheint.

2023-05-09 15:21 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    Please do not use RSA as at least FortiGate seems to have a problem with RSA keys.<br>
For legacy ssh based FortiGate, do not use RSA as there seems to be a problem with RSA keys.

2023-05-09 15:21 UTC, tpurschke commented on roles/ui/files/FWO.UI/wwwroot/css/bootstrap/bootstrap.min.css
>   * Copyright 2011-2020 The Bootstrap Authors
why/how was the bootstrap.css file changed?

2023-05-10 11:13 UTC, abarz722 commented on roles/ui/files/FWO.UI/wwwroot/css/bootstrap/bootstrap.min.css
>   * Copyright 2011-2020 The Bootstrap Authors
changed the color of alert-warning: did an override in side.css instead now

2023-05-10 17:20 UTC, tpurschke requested changes

2023-05-10 17:20 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    F&uuml;r Fortinet, Barracuda, Juniper muss die IP vom aufl&ouml;sbaren Namen des Firewallgateways spezifiziert werden.<br>
F&uuml;r alle Firewall-Plattformen, die kein separates Management-System besitzen, muss die IP oder der aufl&ouml;sbare Name des Firewallgateways spezifiziert werden.

2023-05-10 17:20 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    F&uuml;r alle &uuml;brigen Firewall-Plattformen, bei denen es es kein separates Management gibt, muss die IP oder der aufl&ouml;sbare Name des Firewallgateways spezifiziert werden.
can be removed

2023-05-10 17:20 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    For Fortinet, Barracuda, Juniper you need to specify the IP or resolvable name of the firewall gateway.<br>
remove this sentence

2023-05-10 17:20 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +    For all other firewall platforms which do not possess a separate management, use the IP address or the resolvable name of the firewall gateway.
For all firewall platforms which do not possess a separate management, use the IP address or the resolvable name of the firewall gateway.

2023-05-10 17:20 UTC, tpurschke commented on roles/ui/files/FWO.UI/wwwroot/css/bootstrap/bootstrap.min.css
>   * Copyright 2011-2020 The Bootstrap Authors
sounds good - but in this case there should not be any changes to the boostrap.css at all, right?

2023-05-11 05:54 UTC, tpurschke approved these changes

2023-05-11 05:54 UTC, merged