Rework ExtRequest Templates
CactuseSecurity/firewall-orchestrator pull request #2631
Opened 2024-11-03 07:08 UTC by abarz722

Sub templates now also in settings (object,...)

2024-11-04 07:54 UTC, tpurschke requested changes
also, the management_id for each group member needs to be re-added

2024-11-04 07:54 UTC, tpurschke commented on roles/lib/files/FWO.Tufin.SecureChange/SCTicketTask.cs
> +		// 		"object_details": "10.192.222.165/32",
We should further anonymize App Server Name and definetly IP

2024-11-04 07:54 UTC, tpurschke commented on roles/lib/files/FWO.Tufin.SecureChange/SCTicketTask.cs
> +		// 		"name": "tufin_virt_ip_10.192.222.166",
Here as well

2024-11-05 16:05 UTC, tpurschke reviewed
```
2024-11-05T16:46:00.384856+01:00 xxx fworch.middleware-server:  2024-11-05T16:46:00+01:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call  in role middleware-server: mutation updateExtRequestCreation(  $id: bigint!  $extRequestState: ... with variables: {"id":93,"extRequestState":"ExtReqFailed","extTick...
2024-11-05T16:46:00.391234+01:00 xxx fworch.middleware-server:  2024-11-05T16:46:00+01:00 Error - Error while creating external ticket (ExternalRequestSender.cs in line 114), Error Message: , {"result":{"code":"FIELD_VALIDATION_ERROR","message":"Invalid value for field: Modify group (Network object with name NetworkObjectKey{name='lxm02708.xxx.de', uid='null', managementId=null, managementName=null} in group AR5004515-001 does not exist)"}}

```
mgm_id not filled?

2024-11-06 06:10 UTC, tpurschke approved these changes

2024-11-06 06:36 UTC, abarz722 commented
Hi Tim,
 
die Management-Id fehlt wahrscheinlich nur im Template: meine neue Version:
Template Objekt:
 
***@***.***": "@@TYPE@@", "name": "@@OBJECTNAME@@", "object_type": "@@OBJECT_TYPE@@", "object_details": "@@OBJECT_DETAILS@@", "management_id": @@MANAGEMENT_ID@@,"status": "@@STATUS@@", "comment": "@@COMMENT@@", "object_updated_status": "@@OBJUPDSTATUS@@"}
 
Template Objekt kurz:
 
***@***.***": "Object","name": "@@OBJECTNAME@@","management_id": @@MANAGEMENT_ID@@,"status": "@@STATUS@@","object_updated_status": "@@OBJUPDSTATUS@@"}
 
Gruß
Achim
 


Gesendet: Dienstag, 5. November 2024 um 17:05
Von: "Tim Purschke" ***@***.***>
An: CactuseSecurity/firewall-orchestrator ***@***.***>
CC: abarz722 ***@***.***>,Author ***@***.***>
Betreff: Re: [CactuseSecurity/firewall-orchestrator] Rework ExtRequest Templates (PR #2631)

 
@tpurschke commented on this pull request.
so, sieht besser aus, aber beim ERstellen der Reduzierungstickets kommt ein FEhler
2024-11-05T16:46:00.384856+01:00 lxm02199 fworch.middleware-server: 2024-11-05T16:46:00+01:00 Debug - API call (GraphQlApiConnection.cs in line 129), Sending API call in role middleware-server: mutation updateExtRequestCreation( $id: bigint! $extRequestState: ... with variables: {"id":93,"extRequestState":"ExtReqFailed","extTick...2024-11-05T16:46:00.391234+01:00 lxm02199 fworch.middleware-server: 2024-11-05T16:46:00+01:00 Error - Error while creating external ticket (ExternalRequestSender.cs in line 114), Error Message: , {"result":{"code":"FIELD_VALIDATION_ERROR","message":"Invalid value for field: Modify group (Network object with name NetworkObjectKey{name='lxm02708.ruv.de', uid='null', managementId=null, managementName=null} in group AR5004515-001 does not exist)"}}
kann es sein, dass hier einige Felder noch nicht gefüllt werden? Das Objekt scheint nämlich drin zu sein:
mgm_id?14m
—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-11-06 11:44 UTC, merged