Merge develop branches
CactuseSecurity/firewall-orchestrator pull request #2634
Opened 2024-11-05 11:14 UTC by SolidProgramming

Includes some tests for #2597
Includes turn creation of app zones on/off
Includes make the syntax (AZ) configurable as application zone prefix

2024-11-05 11:33 UTC, SolidProgramming commented
@tpurschke okay...before i push the merge with solved conflicts we should take a look at it together before i break the develop branch completly...

2024-11-06 06:53 UTC, tpurschke requested changes

2024-11-06 06:53 UTC, tpurschke commented on roles/lib/files/FWO.Api.Client/FWO.Api.Client.csproj
> +    <ProjectReference Include="..\..\..\GlobalFuncs\FWO.GlobalFunctions.csproj" />
This should be FWO.Basics

2024-11-07 10:53 UTC, abarz722 commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +INSERT INTO txt VALUES ('app_zone_pattern',		'German', 	'App Zone Pattern');
Languages mixed up

2024-11-07 11:52 UTC, abarz722 approved these changes

2024-11-07 12:56 UTC, tpurschke approved these changes

2024-11-07 12:56 UTC, merged