Merge AppZone creation into develop
CactuseSecurity/firewall-orchestrator pull request #2683
Opened 2024-11-26 09:09 UTC by SolidProgramming

Closes #2597

2024-11-26 17:01 UTC, tpurschke requested changes
clicking the request fw changes button once results in AZ change being planned.
but when aborting via cancel button and clicking the request button a second time, the AZ change is not planned.
when restarting the UI, the AZ change is part of the implementation plan again (but again just once).

2024-11-28 12:25 UTC, abarz722 requested changes
there are some things to be simplified

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Api.Client/Data/ModellingAppZone.cs
> +        private static List<ModellingAppServerWrapper> ConvertNwObjectsToAppServers(GroupFlat<NetworkObject>[] groupFlats)
Same method as in base class ? Make protected in ModellingAppRole and use it from there

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +        private ModellingAppZoneHandler AppZoneHandler = new(apiConnection, userConfig, displayMessageInUi);
The owner could be directly propagated to the AppZoneHandler via constructor: Add it as member to to ModellingVarianceAnalysis and feed the constructor in RequestFwChangePopup.razor with "SelectedApp".
This would save a lot owner lookups and owner parameters in the method calls

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingAppZoneHandler.cs
> +            List<FwoOwner> owners = await apiConnection.SendQueryAsync<List<FwoOwner>>(OwnerQueries.getOwners);
owner lookup obsolete when given by constructor

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingAppZoneHandler.cs
> +            FwoOwner? owner = owners.FirstOrDefault(_ => _.Id == appId);
owner lookup obsolete when given by constructor

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/AppZoneStateHelper.cs
> +    internal static class AppZoneStateHelper
Do we still need this class?

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingAppZoneHandler.cs
> +        public async Task<ModellingAppZone?> CreateAppZone(ModellingConnection conn, FwoOwner owner)
method can be removed

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingAppZoneHandler.cs
> +                appZone = new()
use CreateAppZone() here (and move AppServer lookup to else branch)

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +
only the app zone object (identified by name?) should be written to ExistingProdAppZones (and not to allExistingAppRoles)

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +            ExistingProdAppZones = AppZoneStateHelper.GetManagementAppZones();
obsolete?

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +                WfReqTask? taskEntryNewAppZone = TaskList.FirstOrDefault(x => x.Title == userConfig.GetText("new_app_zone") + existingAppZone.IdString && x.OnManagement?.Id == mgt.Id);
there can't be more than one appZone, so there can't be any of these tasks in the TaskList when analyzing. So this check should be obsolete.

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +            AppZoneStateHelper.SetManagementAppZones(ExistingProdAppZones);
obsolete?

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +        private Dictionary<int, List<ModellingAppZone>> alreadyCreatedAppZones = [];
as we have only one appZone this list and its usage below is not necessary

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +                    CreateAppZoneTaskListEntry(existingAppZone, mgt);
If app zone is not new or changed we don't need any task in the list -> remove this method

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +        private bool AppZoneAlreadyRequested(ModellingAppZone appZone, Management mgt)
remove

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +        private void FillGroupMembersAppZone(ModellingAppZone appZone, Management mgt)
use FillGroupMembers (after changing parameter appRole into idstring, as only this is used inside) also here instead of duplicating the whole code

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +        private List<WfReqElement> GetAppZoneGroupMembers(ModellingAppZone appZone, Management mgt)
remove

2024-11-28 12:25 UTC, abarz722 commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +            if (!ExistingProdAppZones.ContainsKey(mgt.Id))
not necessary

2024-11-29 12:08 UTC, SolidProgramming commented on roles/lib/files/FWO.Services/ModellingAppZoneHandler.cs
> +            List<FwoOwner> owners = await apiConnection.SendQueryAsync<List<FwoOwner>>(OwnerQueries.getOwners);
I personally don't like constructors with many parameters but this makes sense, thanks!

2024-11-29 12:09 UTC, SolidProgramming commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +        private ModellingAppZoneHandler AppZoneHandler = new(apiConnection, userConfig, displayMessageInUi);
I personally don't like constructors with too many parameters but this makes sense, thanks!

2024-11-29 12:15 UTC, SolidProgramming commented on roles/lib/files/FWO.Services/AppZoneStateHelper.cs
> +    internal static class AppZoneStateHelper
Due this PR still beeing in draft, yes i need that for testing so i can simulate prode state of FW.

2024-12-04 12:45 UTC, tpurschke requested changes

2024-12-04 12:45 UTC, tpurschke commented on .gitignore
> +/roles/lib/files/FWO.Services/AppZoneStateHelper.cs
what is this? Test data?

2024-12-04 12:45 UTC, tpurschke commented on roles/database/files/sql/idempotent/fworch-texts.sql
> +INSERT INTO txt VALUES ('app_owner_not_found',  'German',   'Keinen Owner für diese App gefunden');
Eigent&uuml;mer instead of owner in German

2024-12-04 12:45 UTC, tpurschke commented on roles/lib/files/FWO.Config.Api/FWO.Config.Api.csproj
> +    <PackageReference Include="System.Text.Encodings.Web" Version="9.0.0" />
have you tested this now - where do we really need this package?

2024-12-04 12:45 UTC, tpurschke commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +
this seems to be an issue which needs to be resolved?!

2024-12-04 12:45 UTC, tpurschke commented on roles/lib/files/FWO.Services/ModellingVarianceAnalysis.cs
> +                WfReqTask? taskEntryNewAppZone = TaskList.FirstOrDefault(x => x.Title == userConfig.GetText("new_app_zone") + existingAppZone.IdString && x.OnManagement?.Id == mgt.Id);
again - this is an issue to resolve. Can you two @abarz722 , @SolidProgramming talk this though?

2024-12-04 17:28 UTC, tpurschke approved these changes
now, the two open discussions are gone?!

2024-12-04 17:29 UTC, tpurschke commented
> there are some things to be simplified

@abarz722 anything open from your point of view?

2024-12-04 19:15 UTC, abarz722 approved these changes
Looks like my remarks are solved now

2024-12-04 20:33 UTC, merged