Merge fork dev into cactus dev
CactuseSecurity/firewall-orchestrator pull request #2704
Opened 2024-12-08 09:14 UTC by Robin-Smets

**#2610: UI - checkbox should span text field everywhere** 

- added ids to checkboxes
- added references to corresponding labels
- provided method for special case, where a div is used as a label and therefore has no "for" property

**#2602 (CSV)FileUpload Component Rework**

- created generic file upload component "FileUpload"
- created corresponding service "FileUploadService"

2024-12-10 12:17 UTC, SolidProgramming requested changes

2024-12-10 12:17 UTC, SolidProgramming commented on roles/ui/files/FWO.UI/Pages/NetworkModelling/NetworkModelling.razor
> +                                        <label id="cbx_show_rejected"  class="col-form-label">@(userConfig.GetText("displayRejected")):</label>
id and for attributes need to be switched.

2024-12-10 12:17 UTC, SolidProgramming commented on roles/ui/files/FWO.UI/Pages/Settings/SettingsCustomTexts.razor
> +            <input for="cbx_case_sensitive" class="form-check-input" type="checkbox" @bind="caseSensitive">
id and for attributes need to be switched.

2024-12-10 12:17 UTC, SolidProgramming commented on roles/ui/files/FWO.UI/Pages/Settings/SettingsCustomTexts.razor
> +            <input for="cbx_ignore_helptexts" class="form-check-input" type="checkbox" @bind="ignoreHelpTexts">
id and for attributes need to be switched.

2024-12-10 12:28 UTC, Robin-Smets commented on roles/ui/files/FWO.UI/Pages/Settings/SettingsCustomTexts.razor
> +            <input for="cbx_ignore_helptexts" class="form-check-input" type="checkbox" @bind="ignoreHelpTexts">
Yeah, I will change that. Also I forked from the wrong branch. I forked from main, while it should have been develop, right?

2024-12-11 10:24 UTC, closed without merging

2024-12-12 10:01 UTC, SolidProgramming commented on roles/ui/files/FWO.UI/Pages/Settings/SettingsCustomTexts.razor
> +            <input for="cbx_ignore_helptexts" class="form-check-input" type="checkbox" @bind="ignoreHelpTexts">
> Yeah, I will change that. Also I forked from the wrong branch. I forked from main, while it should have been develop, right?

Yes. If you followed the installation instruction in the docs the default branch(main) ist cloned/installed. You can use `git clone https://github.com/CactuseSecurity/firewall-orchestrator.git -b develop` to install the develop branch version of the server instead the main branch version documented in the installation instructions.